apiVersion: v1
kind: Service
metadata:
  name: kr-service
  labels:
    app: kr-app
    tier: backend
spec:
  type: NodePort
  ports:
    - name: http2
      nodePort: 32000
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: kr-app
    tier: backend
